name: MHI
favicon: null
layout_spectrum: 0.74233
typography_spectrum: 0.48933
title: Mazzone Heavy Industries LLC
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-49242901-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b8daff'
    - '#232e28'
    - '#a7b5be'
    - '#7a909e'
  brandStrength: 0.1875
  lightness: 0.6875
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
