layout_spectrum: 0.5629165
typography_spectrum: 0.4026435
color:
  saturation: 0.6931928
  lightness: 0.8292612
  brandStrength: 0.6070386
  rhythmicContrast: 0.1142364
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: MHI
